### ISSUE TITLE
FsSrGen.exe --> fssrgen.exe

### ISSUE THREAD

**Issue by dsyme** [fsprojects/FsSrGen#4]
See comment [here](https://github.com/fsprojects/FsSrGen/commit/b7eade143a2ebb8054db4c1818bc3583ec7b5caa#commitcomment-17026604)

> On a case-sensitive file system, the  tool name in the nuget package is `FsSrGen.exe` but the toolname here is `fssrgen.exe`.   Probably normalizing to `fssrgen.exe` would be best, following `fslex.exe` and `fsyacc.exe`

Fixed by somewhat accidental direct commit to master https://github.com/fsprojects/FsSrGen/commit/894051766747c4aa2667122523f7b89404453dd3#diff-fc3789241aa5d3723856b12d0473e637

This records the correspnding issue since the fix needs to be verified and the nuget packages need to be republished.

**Comment by dsyme** [comment]
@enricosada Could you publish new nuget packages for FsSrGen that include this fix please?  Thanks

**Comment by enricosada** [comment]
sure

**Comment by dsyme** [comment]
@enricosada In 2.0.1 the binary is still called `FsSrGen.exe`.  Did you pull master to your machine before building the new packages?  Thanks

**Comment by enricosada** [comment]
@dsyme published 3.0.0 and sent visualfsharp a pr Microsoft/visualfsharp#1064 to use that package
name is `fssrgen.exe`

**Comment by dsyme** [comment]
Very strangely when I specify 

```
<package id="FsSrGen" version="3.0.0" targetFramework="net46" />
```

I now get a directory called

```
packages\fssrgen.3.0.0\...
```

where it was before

```
packages\FsSrGen.3.0.0\...
```

Very strange!  Nuget shows the right package name. The `create_packages.ps1`  must pick up the name `fssrgen` from somewhere. 

Not sure it matters, it's just a bit odd.

**Comment by enricosada** [comment]
New package is `fssrgen` (lowercase), nuget is case insensitive but use real name when restored

inside this repo, it's the name of the directory.

by default (.net cli) the name of package AND assembly is the name of the directory of `project.json`. I think that's a really good **default**

you can change the package name with the `name` property in project.json
you can change the assembly name with the `compilationOptions.outputName` property in project.json (BUT the current lkg .net cli used with f# it's old and doenst have that proeprty, was committed 20days ago, and yes, .net cli improve fast)

I was thinking was more simple to have the same name `fssrgen` for both package and assembly.
So i changed the name of directory from `FsSrGen` => `fssrgen` :smile: 

I can try to do package = `FsSrGen` and assembly `fssrgen`, but we need to wait a newer lkg or tweak a bit, as you wish @dsyme

**Comment by enricosada** [comment]
btw @dsyme fixed the case in visualfsharp with Microsoft/visualfsharp@9e72d0c1b22f2a8d91e7e7e047def11637acb773

**Comment by enricosada** [comment]
nvm @dsyme , the `compilerOptions.outputName` is already supported!
i'll can fix with package = `FsSrGen` and assembly `fssrgen.exe` if you want

**Comment by dsyme** [comment]
No need to fix until there's some other issue, thanks!
