### ISSUE TITLE
fssrgen.exe is in "lib\net46", should be in "tools"?

### ISSUE THREAD

**Issue by dsyme** [fsprojects/FsSrGen#5]
Should "fssrgen.exe" be in "tools"?

**Comment by dsyme** [comment]
Or would that not apply for .NET Core?

**Comment by enricosada** [comment]
if it's in lib (where .net cli create it), it's possible to `dotnet run` it.
I think it's the right place, also .net core is in the same dir `lib/netstandard1.5`

**Comment by dsyme** [comment]
OK, thanks!

**Comment by dsyme** [comment]
Whoops - the package name is
